ASP_EF/Areas/Admin/Pages/User/AddRole.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using ASP_EF.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ASP_EF.Areas.Admin.Pages.User
{
    public class AddRoleModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly MyBlogContext _context;

        public AddRoleModel(
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager,
            RoleManager<IdentityRole> roleManager,
            MyBlogContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;
        }


        [TempData]
        public string StatusMessage { get; set; }

        public AppUser User { get; set; }

        [BindProperty]
        [DisplayName("Các role gán cho user")]
        public string[] RoleNames { get; set; }

        public SelectList AllRoles { get; set; }

        public List<IdentityRoleClaim<string>> ClaimInRole { get; set; }
        public List<IdentityUserClaim<string>> ClaimInUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Không có User");
            }

            User = await _userManager.FindByIdAsync(id);

            if (User == null)
            {
                return NotFound($"Không tìm thấy User với ID = '{id}'.");
            }

            RoleNames = (await _userManager.GetRolesAsync(User)).ToArray();

            List<string> listRoleNames = await _roleManager.Roles.Select(r => r.Name).ToListAsync();
            AllRoles = new SelectList(listRoleNames);

            await GetClaims(id);

            return Page();
        }

        public async Task GetClaims(string id)
        {
            // List Role này là của User
            var listRoles = from r in _context.Roles
                            join ur in _context.UserRoles
                            on r.Id equals ur.RoleId
                            where ur.UserId == id
                            select r;

            var _claimInRole = from c in _context.RoleClaims
                               join r in listRoles on c.RoleId equals r.Id
                               select c;

            ClaimInRole = await _claimInRole.ToListAsync();

            ClaimInUser = await (from r in _context.UserClaims
                                 where r.UserId == id
                                 select r).ToListAsync();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Không có User");
            }

            User = await _userManager.FindByIdAsync(id);

            if (User == null)
            {
                return NotFound($"Không tìm thấy User với ID = '{id}'.");
            }

            await GetClaims(id);

            // RoleNames
            var oldRoleNames = (await _userManager.GetRolesAsync(User)).ToArray();

            var deleteRole = oldRoleNames.Where(r => !RoleNames.Contains(r));
            var addRole = RoleNames.Where(r => !oldRoleNames.Contains(r));

            List<string> listRoleNames = await _roleManager.Roles.Select(r => r.Name).ToListAsync();
            AllRoles = new SelectList(listRoleNames);

            var resultDelete = await _userManager.RemoveFromRolesAsync(User, deleteRole);
            if(!resultDelete.Succeeded)
            {
                resultDelete.Errors.ToList().ForEach(error =>
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                });
                return Page();
            }

            var resultAdd = await _userManager.AddToRolesAsync(User, addRole);
            if (!resultAdd.Succeeded)
            {
                resultAdd.Errors.ToList().ForEach(error =>
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                });
                return Page();
            }

            StatusMessage = $"Đã cập nhật role cho: {User.UserName}";

            return RedirectToPage("./Index");
        }

    }
}

ASP_EF/Areas/Admin/Pages/User/EditUserRoleClaim.cshtml.cs
using ASP_EF.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace ASP_EF.Areas.Admin.Pages.User
{
    public class EditUserRoleClaimModel : PageModel
    {
        private readonly MyBlogContext _context;
        private readonly UserManager<AppUser> _userManager;
        public EditUserRoleClaimModel(MyBlogContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [TempData]
        public string StatusMessage { get; set; }

        public NotFoundObjectResult OnGet() => NotFound("Không được truy cập");

        public class InputModel
        {
            [DisplayName("Kiểu (tên) claim")]
            [Required(ErrorMessage = "Phải nhập {0}")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "{0} phải dài từ {2} đến {1} ký tự")]
            public string ClaimType { get; set; }

            [DisplayName("Giá trị của claim")]
            [Required(ErrorMessage = "Phải nhập {0}")]
            [StringLength(256, MinimumLength = 3, ErrorMessage = "{0} phải dài từ {2} đến {1} ký tự")]
            public string ClaimValue { get; set; }
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public AppUser User { get; set; }

        public async Task<IActionResult> OnGetAddClaimAsync(string userid)
        {
            User = await _userManager.FindByIdAsync(userid);
            if(User == null)
                return NotFound("Không tìm thấy user");

            return Page();
        }

        public IdentityUserClaim<string> UserClaim { get; set; }

        public async Task<IActionResult> OnPostAddClaimAsync(string userid)
        {
            User = await _userManager.FindByIdAsync(userid);
            if (User == null)
                return NotFound("Không tìm thấy user");

            if(!ModelState.IsValid) return Page();

            // Danh sách các claim của User
            var claims = _context.UserClaims.Where(c => c.UserId == User.Id);
            
            if(claims.Any(c => c.ClaimType == Input.ClaimType && c.ClaimValue == Input.ClaimValue))
            {
                ModelState.AddModelError(string.Empty, "Đặc tính (claim) này đã có");
                return Page();
            }

            await _userManager.AddClaimAsync(User, new Claim(Input.ClaimType, Input.ClaimValue));
            StatusMessage = "Đã thêm đặc tính (claim) cho User";

            return RedirectToPage("./AddRole", new {id = User.Id});
        }

        public async Task<IActionResult> OnGetEditClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("Không tìm thấy User");

            UserClaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();
            User = await _userManager.FindByIdAsync(UserClaim.UserId);
            if (User == null)
                return NotFound("Không tìm thấy user");

            Input = new()
            {
                ClaimType = UserClaim.ClaimType,
                ClaimValue = UserClaim.ClaimValue
            };

            return Page();
        }

        public async Task<IActionResult> OnPostEditClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("Không tìm thấy User");

            UserClaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();
            User = await _userManager.FindByIdAsync(UserClaim.UserId);
            if (User == null)
                return NotFound("Không tìm thấy user");

            if(!ModelState.IsValid) return Page();

            if(_context.UserClaims.Any(c => c.UserId == User.Id
                && c.ClaimType == Input.ClaimType
                && c.ClaimValue == Input.ClaimValue
                && c.Id != claimid))
            {
                ModelState.AddModelError(string.Empty, "Claim này đã có");
            }

            UserClaim.ClaimType = Input.ClaimType;
            UserClaim.ClaimValue = Input.ClaimValue;

            await _context.SaveChangesAsync();
            StatusMessage = "Bạn vừa cập nhật claim";

            return RedirectToPage("./AddRole", new { id = User.Id });
        }

        public async Task<IActionResult> OnPostDeleteClaimAsync(int? claimid)
        {
            if (claimid == null) return NotFound("Không tìm thấy User");

            UserClaim = _context.UserClaims.Where(c => c.Id == claimid).FirstOrDefault();
            User = await _userManager.FindByIdAsync(UserClaim.UserId);
            if (User == null) return NotFound("Không tìm thấy user");

            await _userManager.RemoveClaimAsync(User, new Claim(UserClaim.ClaimType, UserClaim.ClaimValue));

            StatusMessage = "Bạn vừa xóa claim";

            return RedirectToPage("./AddRole", new { id = User.Id });
        }
    }
}

ASP_EF/Areas/Admin/Pages/User/Index.cshtml.cs
using ASP_EF.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ASP_EF.Areas.Admin.Pages.User
{
    public class IndexModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;
        public IndexModel(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        public class UserAndRole : AppUser
        {
            public string RoleNames { get; set; }
        }
        public List<UserAndRole> Users { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        // Paging
        public const int ITEMS_PER_PAGE = 10;

        [BindProperty(SupportsGet = true, Name = "p")]
        public int CurrentPage { get; set; }
        public int TotalPage { get; set; }
        public int TotalUsers { get; set; }

        public async Task OnGetAsync()
        {
            // Users = await _userManager.Users.OrderBy(u => u.UserName).ToListAsync();
            var qr = _userManager.Users.OrderBy(u => u.UserName);

            TotalUsers = await qr.CountAsync();
            TotalPage = (int)Math.Ceiling((double)TotalUsers / ITEMS_PER_PAGE);

            if (CurrentPage < 1)
                CurrentPage = 1;
            if (CurrentPage > TotalPage)
                CurrentPage = TotalPage;

            var qr1 = qr.Skip((CurrentPage - 1) * ITEMS_PER_PAGE)
                        .Take(ITEMS_PER_PAGE)
                        .Select(u => new UserAndRole()
                        {
                            Id = u.Id,
                            UserName = u.UserName
                        });

            Users = await qr1.ToListAsync();

            foreach(var user in Users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                user.RoleNames = string.Join(", ", roles);
            }
        }

        public void OnPost() => RedirectToPage();
    }
}

ASP_EF/Areas/Admin/Pages/User/SetPassword.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using ASP_EF.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP_EF.Areas.Admin.Pages.User
{
    public class SetPasswordModel : PageModel
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public SetPasswordModel(
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        public class InputModel
        {
            [Required(ErrorMessage = "Phải nhập {0}")]
            [StringLength(100, ErrorMessage = "{0} phải dài từ {2} đến {1} ký tự.", MinimumLength = 3)]
            [DataType(DataType.Password)]
            [Display(Name = "Mật khẩu mới")]
            public string NewPassword { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Xác nhận mật khẩu")]
            [Compare("NewPassword", ErrorMessage = "Lặp lại mật khẩu không chính xác.")]
            public string ConfirmPassword { get; set; }
        }

        public AppUser User { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Không có User");
            }

            User = await _userManager.FindByIdAsync(id);

            if (User == null)
            {
                return NotFound($"Không tìm thấy User với ID = '{id}'.");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Không có User");
            }

            User = await _userManager.FindByIdAsync(id);

            if (User == null)
            {
                return NotFound($"Không tìm thấy User với ID = '{id}'.");
            }
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _userManager.RemovePasswordAsync(User);

            var addPasswordResult = await _userManager.AddPasswordAsync(User, Input.NewPassword);
            if (!addPasswordResult.Succeeded)
            {
                foreach (var error in addPasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return Page();
            }

            StatusMessage = "Đã cập nhật mật khẩu cho User.";

            return RedirectToPage("./Index");
        }
    }
}

ASP_EF/Areas/Admin/Pages/User/AddRole.cshtml
@page "/admin/assign-user-role/{id}"
@model AddRoleModel
@{
    ViewData["Title"] = "Gán role";
}

<h3>Thiết lập role cho user: @Model.User.UserName</h3>
<partial name="_StatusMessage" for="StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form id="set-password-form" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
            <div class="form-group mb-4">
                <label asp-for="RoleNames" class="form-label"></label>
                @Html.ListBoxFor(m => m.RoleNames, Model.AllRoles, new {
                    id = "id-select-roles",
                    @class = "w-100"
                })
                <span asp-validation-for="RoleNames" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Cập nhật</button>
            <a class="btn btn-secondary" asp-page="./Index">Danh sách thành viên</a>
        </form>
        <hr />
        <p>Các claim của User có được từ role:</p>
        @if(Model.ClaimInRole.Count > 0)
        {
            <ul>
                @foreach(var claim in Model.ClaimInRole)
                {
                    <li>@claim.ClaimType : @claim.ClaimValue</li>
                }
            </ul>
        }

        <p>
            Các claim riêng:
            <a asp-page="./EditUserRoleClaim" asp-page-handler="AddClaim" asp-route-userid="@Model.User.Id">+ thêm claim riêng</a>
        </p>
        @if (Model.ClaimInUser.Count > 0)
        {
            <ul>
                @foreach (var claim in Model.ClaimInUser)
                {
                    <li>
                        <a asp-page="./EditUserRoleClaim" asp-page-handler="EditClaim"  asp-route-claimid="@claim.Id">@claim.ClaimType : @claim.ClaimValue</a>
                    </li>
                }
            </ul>
        }
    </div>
</div>


@section Scripts {

    <script src="~/lib/multiple-select/multiple-select.min.js"></script>
    <link rel="stylesheet" href="~/lib/multiple-select/multiple-select.min.css" />

    <script>
        $("#id-select-roles").multipleSelect({
            selectAll: false,
            keepOpen: false,
            isOpen: false,
            placeholder: "Chọn role ..."
        });
    </script>
    
    <partial name="_ValidationScriptsPartial" />
}

ASP_EF/Areas/Admin/Pages/User/EditUserRoleClaim.cshtml
@page "/admin/edit-user-claim/{userid?}"
@model ASP_EF.Areas.Admin.Pages.User.EditUserRoleClaimModel
@{
    ViewData["Title"] = "Claim của User";
}

<h1>@ViewData["Title"]: @Model.User.UserName</h1>
<partial name="_StatusMessage" for="StatusMessage" />

<hr />
<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.ClaimType" class="control-label"></label>
                <input asp-for="Input.ClaimType" class="form-control" />
                <span asp-validation-for="Input.ClaimType" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Input.ClaimValue" class="control-label"></label>
                <input asp-for="Input.ClaimValue" class="form-control" />
                <span asp-validation-for="Input.ClaimValue" class="text-danger"></span>
            </div>

            <div class="form-group mt-2">
                @if(Model.UserClaim != null)
                {
                    <input type="submit" value="Cập nhật" class="btn btn-primary" />
                    <input type="submit" value="Xóa" asp-route-claimid="@Model.UserClaim.Id" asp-page-handler="DeleteClaim" class="btn btn-danger" />
                }
                else
                {
                    <input type="submit" value="Tạo mới" class="btn btn-primary" />
                }

                <a class="btn btn-secondary" asp-page="./AddRole" asp-route-id="@Model.User.Id">Chỉnh sửa User</a>
            </div>
        </form>
    </div>
</div>

ASP_EF/Areas/Admin/Pages/User/Index.cshtml
@page "/admin/members"
@model ASP_EF.Areas.Admin.Pages.User.IndexModel
@{
    ViewData["Title"] = "Danh sách các thành viên";
}

<h2>@ViewData["Title"]</h2>

<partial name="_StatusMessage" model="@Model.StatusMessage" />
<p>Tổng số User: @Model.TotalUsers</p>
<p>Tổng số trang: @Model.TotalPage</p>

<table class="table">
    <tr>
        <th>Tên User</th>
        <th>Vai trò (role)</th>
        <th>Tác vụ</th>
    </tr>
    @foreach (var user in Model.Users)
    {
        <tr>
            <td>@user.UserName</td>
            <td>
                @if (string.IsNullOrEmpty(user.RoleNames))
                {
                    <a class="text-dark text-decoration-none badge bg-secondary fs-6" asp-page="./AddRole" asp-route-id="@user.Id">+ Thêm role</a>
                }
                else
                {
                    <a asp-page="./AddRole" asp-route-id="@user.Id">@user.RoleNames</a>
                }
            </td>
            <td>
                <a class="btn btn-success btn-sm text-decoration-none" asp-page="./SetPassword" asp-route-id="@user.Id">Đặt mật khẩu</a>
            </td>
        </tr>
    }
</table>

@{
    var pagingModel = new ASP_EF.Helpers.PagingModel()
            {
                currentpage = Model.CurrentPage,
                countpage = Model.TotalPage,
                generateUrl = (int? p) => @Url.Page("./Index", new { p = p })
            };
}

<partial name="_Paging" model="@pagingModel" />

ASP_EF/Areas/Admin/Pages/User/SetPassword.cshtml
@page "/admin/set-member-password/{id}"
@model SetPasswordModel
@{
    ViewData["Title"] = "Đặt mật khẩu";
}

<h3>Thiết lập mật khẩu cho thành viên: @Model.User.UserName</h3>
<partial name="_StatusMessage" for="StatusMessage" />

<div class="row">
    <div class="col-md-6">
        <form id="set-password-form" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
            <div class="form-floating mb-3">
                <input asp-for="Input.NewPassword" class="form-control" autocomplete="new-password" placeholder="Please enter your new password."/>
                <label asp-for="Input.NewPassword" class="form-label"></label>
                <span asp-validation-for="Input.NewPassword" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Input.ConfirmPassword" class="form-control" autocomplete="new-password" placeholder="Please confirm your new password."/>
                <label asp-for="Input.ConfirmPassword" class="form-label"></label>
                <span asp-validation-for="Input.ConfirmPassword" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Đặt mật khẩu</button>
            <a class="btn btn-secondary" asp-page="./Index">Danh sách thành viên</a>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ASP_EF/Areas/Admin/Pages/User/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @Model
    </div>
}